dist: xenial
language: go

go:
  - "1.11.x"

branches:
  only:
  - master

env:
  global:
    - CGO_CFLAGS=`pkg-config --cflags luajit`
  matrix:
    - CGO_CFLAGS=`pkg-config --cflags luajit`

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libluajit-5.1-dev

install:
  - go get github.com/kjx98/golib/to

script:
    - go test -v ./...
